services:
  database:
    container_name: db
    image: postgres:12.7
    restart: always
    environment:
      - POSTGRES_USER=healthtone
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
